### ISSUE TITLE
Reporte 2_Diseño grafico

### ISSUE THREAD

**Issue by JoseMVasquezD** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicosa-equiporr#2]
[reporte_2_topicos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicosa-equiporr/files/10777308/reporte_2_topicos.pdf)

**Comment by Elisahadad** [comment]
Calificación: 14
Falta lista de figuras y complementar el desarrollo.

**Comment by josealfredo79** [comment]
Revisado...
